### ISSUE TITLE
You currently must disable cerbere from monitoring wingpanel

### ISSUE THREAD

**Issue by outofpapaer** [mlibre/hide-wingpanel#5]
To prevent Wingpanel from being constantly relaunched we can either manually edit the  io.elementary.desktop.cerbere monitored-processes value using dconf or gsettings. I suggest having the installer parse the current monitored-processes with gsettings:
 ```gsettings get io.elementary.desktop.cerbere monitored-processes```
and then pop wingpanel from the returned list then set the monitored-processes to the new list.
```gsettings set io.elementary.desktop.cerbere monitored-processes ...```

**Comment by mlibre** [comment]
Yes, I think that is a good idea. but honestly, it does not worth.
If elementary has not fixed it, after 1 year of this project. it means something bad is happening there.
The project is dead and they don't work on the OS at all. Maybe the new versions are all being made by scripts. 
Maybe even they have put some sort of virus there :)))) in wing-panel. That is why they don't disable it :))
It all possible. So if you ask me, don't use that OS anymore.
I deleted it after 1 week I guess. After I wrote this script last year.

**Comment by quequotion** [comment]
There are two forks of wingpanel currently in development with real, built-in autohide:

One is [mine](https://github.com/elementary/wingpanel/pull/93), which uses libwnck (like plank) and is unlikely to be adopted upstream; the other is [donadigo's](https://github.com/elementary/wingpanel/pull/212) gala-dependent reimplementation of it, which is more likely to see an official release some day.

Killing and restarting it is one solution to the problem, but this necessitates killing cerbere as well, which is probably not what Pantheon users would want if they realized it was happening (wingpanel and plank won't come back of they ever crash).

For a while the elementary OS devs rejected this issue on a design basis, but they have (slightly) warmed up to it since.

**Comment by mlibre** [comment]
Oh, that is cool. I hope they fix it.
